INSERT INTO products (title, price, description, short_description, brand, category, stock, grade, condition, image_url, is_new, is_sale, is_popular) VALUES
('LQ-300+II', 6890, NULL, 'Dot Matrix Printer', 'Epson', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('LQ-310', 4490, NULL, 'Dot Matrix Printer', 'Epson', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('LQ-590', 4700, NULL, 'Dot Matrix Printer', 'Epson', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('LQ-2090', 3490, NULL, 'Dot Matrix Printer', 'Epson', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('LQ-2190', 4790, NULL, 'Dot Matrix Printer', 'Epson', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('PLQ-200', 2190, NULL, 'Passbook Printer', 'Epson', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('TM-T82II', 1590, NULL, 'Thermal Receipt Printer', 'Epson', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('TM-U220', 2290, NULL, 'Dot Matrix Receipt Printer', 'Epson', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('LQ-2090C', 0, NULL, 'Dot Matrix Printer', 'Epson', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('LQ-630', 2500, NULL, 'Dot Matrix Printer', 'Epson', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('LBP6030', 1590, NULL, 'Laser Printer', 'Canon', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('LBP6030w', 3100, NULL, 'Laser Printer', 'Canon', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('imageCLASS LBP6230dw', 1190, NULL, 'Laser Printer', 'Canon', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('LaserJet P1102', 1690, NULL, 'Laser Printer', 'HP', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('LaserJet P1006', 1390, NULL, 'Laser Printer', 'HP', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('LaserJet Pro M102w', 1890, NULL, 'Laser Printer', 'HP', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('LaserJet Pro MFP M130fn', 2650, NULL, 'Laser Multifunction Printer', 'HP', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('LaserJet Pro MFP M127fn', 2690, NULL, 'Laser Multifunction Printer', 'HP', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('LaserJet Pro 400 M401dn', 5590, NULL, 'Laser Printer', 'HP', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('Color LaserJet Pro MFP M176n', 3490, NULL, 'Color Laser Multifunction Printer', 'HP', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('HL-L2320D', 1690, NULL, 'Laser Printer', 'Brother', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('HL-L2360DN', 2090, NULL, 'Laser Printer', 'Brother', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('HL-5450DN', 2690, NULL, 'Laser Printer', 'Brother', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('DCP-2540DW', 3490, NULL, 'Laser Multifunction Printer', 'Brother', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('MFC-7360', 2490, NULL, 'Laser Multifunction Printer', 'Brother', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('MFC-7860DW', 2690, NULL, 'Laser Multifunction Printer', 'Brother', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('MFC-J2330DW', 0, NULL, 'Inkjet Multifunction Printer', 'Brother', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('MFC-J430W', 0, NULL, 'Inkjet Multifunction Printer', 'Brother', 'เครื่องพิมพ์', 10, 'A', 'มือสอง', NULL, true, false, false),
('LQ-300+II Ribbon', 300, NULL, 'ผ้าหมึก/ริบบอน', 'Epson', 'อะไหล่/ริบบอน', 10, 'A', 'มือสอง', NULL, true, false, false),
('9x11 5 ชั้น', 130, NULL, 'กระดาษต่อเนื่อง', 'Generic', 'กระดาษต่อเนื่อง', 10, 'A', 'มือสอง', NULL, true, false, false),
('Tractor Assy LQ-300+II', 750, NULL, 'ชุดดึงกระดาษ', 'Epson', 'อะไหล่', 10, 'A', 'มือสอง', NULL, true, false, false),
('Tractor Assy LQ-310', 350, NULL, 'ชุดดึงกระดาษ', 'Epson', 'อะไหล่', 10, 'A', 'มือสอง', NULL, true, false, false),
('Main Board LQ-590/LQ-2090', 1490, NULL, 'เมนบอร์ดเครื่องพิมพ์', 'Epson', 'อะไหล่', 10, 'A', 'มือสอง', NULL, true, false, false),
('Power Supply LQ-300+II', 640, NULL, 'เพาเวอร์ซัพพลาย', 'Epson', 'อะไหล่', 10, 'A', 'มือสอง', NULL, true, false, false),
('Printer Head LQ-2190/LQ-2180', 1500, NULL, 'หัวพิมพ์', 'Epson', 'อะไหล่', 10, 'A', 'มือสอง', NULL, true, false, false),
('Printer Head LQ-300/LQ-300+II', 1090, NULL, 'หัวพิมพ์', 'Epson', 'อะไหล่', 10, 'A', 'มือสอง', NULL, true, false, false),
('Cover LQ-300+II', 830, NULL, 'ฝาครอบ/ชิ้นส่วนภายนอก', 'Epson', 'อะไหล่', 10, 'A', 'มือสอง', NULL, true, false, false),
('Paper Eject LQ-590', 500, NULL, 'ชุดทางออกกระดาษ', 'Epson', 'อะไหล่', 10, 'A', 'มือสอง', NULL, true, false, false),
('USB 2.0 Cable', 39, NULL, 'สาย USB', 'Generic', 'อุปกรณ์เสริม', 10, 'A', 'มือสอง', NULL, true, false, false),
('Adapter TM-T82/TM-T82II', 1590, NULL, 'อะแดปเตอร์', 'Epson', 'อุปกรณ์เสริม', 10, 'A', 'มือสอง', NULL, true, false, false),
('TN-2380', 249, NULL, 'Toner Cartridge', 'Brother', 'โทนเนอร์', 10, 'A', 'มือสอง', NULL, true, false, false),
('DR-2355', 0, NULL, 'Drum Unit', 'Brother', 'ดรัม', 10, 'A', 'มือสอง', NULL, true, false, false),
('TN-2280', 249, NULL, 'Toner Cartridge', 'Brother', 'โทนเนอร์', 10, 'A', 'มือสอง', NULL, true, false, false),
('DR-2455', 0, NULL, 'Drum Unit', 'Brother', 'ดรัม', 10, 'A', 'มือสอง', NULL, true, false, false),
('TN-3448', 320, NULL, 'Toner Cartridge', 'Brother', 'โทนเนอร์', 10, 'A', 'มือสอง', NULL, true, false, false),
('DR-3455', 0, NULL, 'Drum Unit', 'Brother', 'ดรัม', 10, 'A', 'มือสอง', NULL, true, false, false),
('TN-3350', 349, NULL, 'Toner Cartridge', 'Brother', 'โทนเนอร์', 10, 'A', 'มือสอง', NULL, true, false, false),
('DR-3335', 0, NULL, 'Drum Unit', 'Brother', 'ดรัม', 10, 'A', 'มือสอง', NULL, true, false, false),
('TN-1000', 199, NULL, 'Toner Cartridge', 'Brother', 'โทนเนอร์', 10, 'A', 'มือสอง', NULL, true, false, false),
('CE285A', 249, NULL, 'Toner Cartridge', 'HP', 'โทนเนอร์', 10, 'A', 'มือสอง', NULL, true, false, false),
('CF230A', 279, NULL, 'Toner Cartridge', 'HP', 'โทนเนอร์', 10, 'A', 'มือสอง', NULL, true, false, false),
('CF232A', 290, NULL, 'Drum Unit', 'HP', 'ดรัม', 10, 'A', 'มือสอง', NULL, true, false, false),
('CF217A', 249, NULL, 'Toner Cartridge', 'HP', 'โทนเนอร์', 10, 'A', 'มือสอง', NULL, true, false, false),
('CF219A', 0, NULL, 'Drum Unit', 'HP', 'ดรัม', 10, 'A', 'มือสอง', NULL, true, false, false),
('CE310A/311A/312A/313A', 279, NULL, 'Color Toner Set', 'HP', 'โทนเนอร์', 10, 'A', 'มือสอง', NULL, true, false, false),
('CE314A', 0, NULL, 'Imaging Drum', 'HP', 'ดรัม', 10, 'A', 'มือสอง', NULL, true, false, false),
('CF283A', 249, NULL, 'Toner Cartridge', 'HP', 'โทนเนอร์', 10, 'A', 'มือสอง', NULL, true, false, false),
('CF248A', 299, NULL, 'Toner Cartridge', 'HP', 'โทนเนอร์', 10, 'A', 'มือสอง', NULL, true, false, false),
('CF279A', 209, NULL, 'Toner Cartridge', 'Canon/HP', 'โทนเนอร์', 10, 'A', 'มือสอง', NULL, true, false, false),
('CE505A', 320, NULL, 'Toner Cartridge', 'HP', 'โทนเนอร์', 10, 'A', 'มือสอง', NULL, true, false, false);